# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63d9b8a987d8dce00e2972f890e5a5c95fe4458db08a9a0654a55b937a301802f5b9c3fa5ce0aae6a3d2a188b1a1f2d70a02cb5611b3d1e0b2aa6b3aaa70e611

test:
  secret_key_base: 3d35186eee75747b38e1b91ba299e8f90f9c49019dea5088b34668b30d90393f1e7bb40da77259883f71652b15320b017567fec3d98013515a56dbb210752e67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
